CONSUMER_KEY = 	"PGTRKK6OKPVSALF9GJJVK7XONACBOKXE"
REDIRECT_URI = "https://localhost/mytest"
JSON_PATH = "C:/Users/ArjunSingh/Desktop/trade/trading_algo/td_state.json"
TD_ACCOUNT = "497876185"
TRANSACTION_ID = ""
